server:
  port: 1111

spring:
  application:
    name: yufan-service-register
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.47.228:1111/eureka/,http://192.168.47.247:1111/eureka/
    register-with-eureka: false
    fetch-registry: false