spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstore?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mymysql
  application:
    name: order

mybatis:
  type-aliases-package: nju.yufan.webstore.order.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

server:
  port: 8024
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 192.168.47.228:8024
  client:
    serviceUrl:
     defaultZone: http://192.168.47.228:1111/eureka/
    fetch-registry: true
    register-with-eureka: true

feign:
  hystrix:
    enabled: true