server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.47.228:1111/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: cart
            uri: lb://cart
            predicates:
              - Path=/cart/**
            filters:
              - StripPrefix=1
        - id: comment
            uri: lb://comment
            predicates:
              - Path=/comment/**
            filters:
              - StripPrefix=1
        - id: goods-service
            uri: lb://goods-service
            predicates:
              - Path=/goods-service/**
            filters:
              - StripPrefix=1
        - id: userservice
            uri: lb://userservice
            predicates:
              - Path=/userservice/**
            filters:
              - StripPrefix=1
        - id: storeservice
            uri: lb://storeservice
            predicates:
              - Path=/storeservice/**
            filters:
              - StripPrefix=1
